### ISSUE TITLE
long poling while stuck

### ISSUE THREAD

**Issue by eylesa** [patzj/long-poll#1]
I've download and install patzj long poll code in my project. thanks. but I have problem with load another page. when I open page1 codes work well, and in dev tools of chrome appear get_status.php as "pending". when I click page2(another page) it still look "pending" and page2 is not open, I think it can close the while loop. can u help me pls?

**Comment by patzj** [comment]
@eylesa Are you trying to do exactly the steps on the readme or are you trying to integrate this on your project? Would you mind linking me to your project or showing me screenshot so I can check it? This repo was actually meant to show my students how real-time updates are done. Hope we can resolve this.

**Comment by eylesa** [comment]
gbcim.com
